INSERT INTO patient(PAID, PANOM, PAPRENOM, PADNAISS, PAADRSS, PAVILLE, PACODEPOSTAL) VALUES(11,'Rhodia','Freude', TO_DATE('1986-02-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),'impasse','Bidart','64210');
UPDATE patient SET PAPRENOM='Freud' WHERE PAID='11';
UPDATE patient SET PAADRSS='19 gy le grand' WHERE PAADRSS='18 gy le grand';

update	ordonnance set ORDESCRIPT='EXPIRER' WHERE PAID = (SELECT PAID FROM patient WHERE PANOM = 'Mal' AND PAPRENOM='Francine');
update	ordonnance set ORDESCRIPT='EXPIRER' WHERE DRID = (SELECT DRID FROM medecin WHERE DRNOM = 'Mont' AND DRPRENOM='Albert');

UPDATE rendezvous SET RVDDEBUT = TO_DATE('2020-09-11 10:47:00', 'YYYY-MM-DD HH24:MI:SS')
 WHERE PAID = (SELECT PAID FROM patient WHERE PANOM = 'Marchand' AND PAPRENOM='Edwige') 
 AND DRID = (SELECT DRID FROM medecin WHERE DRNOM = 'Dupont' AND DRPRENOM='Albert');
 
 
UPDATE rendezvous SET RVDFIN = TO_DATE('2020-09-11 11:47:00', 'YYYY-MM-DD HH24:MI:SS') 
WHERE PAID = (SELECT PAID FROM patient WHERE PANOM = 'Marchand' AND PAPRENOM='Edwige') 
AND SEID = (SELECT SEID FROM secretaire WHERE SENOM = 'Megalo' AND SEPRENOM='Melanie');

DELETE FROM patient WHERE PANOM='Rhodia';
DELETE FROM rendezvous WHERE RVID='10';

DELETE FROM rendezvous WHERE RVDDEBUT=TO_DATE('2020-09-25 11:58:17', 'YYYY-MM-DD HH24:MI:SS') AND PAID = (SELECT PAID FROM patient WHERE PANOM='Macaisse');
DELETE FROM ordonnance WHERE ORDATE=TO_DATE('2020-05-11 15:08:11', 'YYYY-MM-DD HH24:MI:SS') AND DRID = (SELECT DRID  FROM medecin WHERE DRNOM='Mont');

DELETE FROM rendezvous WHERE  PAID = (SELECT PAID FROM patient WHERE PANOM ='Marchand' AND PAPRENOM ='Edwige') AND DRID = (SELECT DRID  FROM medecin WHERE DRNOM='Dupont');
DELETE FROM ordonnance WHERE  PAID = (SELECT PAID FROM patient WHERE PANOM ='Dejob' AND PAPRENOM ='Jade') AND DRID = (SELECT DRID  FROM medecin WHERE DRNOM='Coquilles');


SELECT PANOM , paville FROM patient GROUP BY paville, panom;
SELECT PANOM , paprenom, paadrss, paville FROM patient ORDER BY panom;
SELECT PAADRSS, PAVILLE, PACODEPOSTAL FROM patient WHERE PANOM='Dejob' AND PAPRENOM='Sonia';
SELECT PANOM, PAPRENOM FROM patient WHERE PAADRSS='45 chemin des sapins';
SELECT DRNOM, DRPRENOM FROM medecin;

SELECT DRNOM, ORDESCRIPT FROM medecin m, ordonnance o WHERE m.DRID = o.DRID(+);
SELECT DRNOM , RVDDEBUT FROM medecin m, rendezvous r WHERE m.DRID = r.DRID GROUP BY m.DRNOM, r.RVDDEBUT;
SELECT DISTINCT SENOM, SEPRENOM FROM secretaire s, rendezvous r WHERE r.PAID = 6 AND s.SEID = r.SEID;
SELECT PANOM, PAPRENOM, ORDESCRIPT FROM patient p, ordonnance o WHERE p.PAID = o.PAID;
SELECT DRNOM, DRPRENOM, RVDDEBUT, RVDFIN FROM medecin m, rendezvous r WHERE m.DRID = r.DRID;

SELECT PANOM, PAPRENOM, DRNOM, DRPRENOM, RVDDEBUT FROM patient p, medecin m, rendezvous r WHERE r.PAID = p.PAID(+) AND m.DRID = r.DRID(+);
SELECT PANOM, DRNOM , RVDDEBUT FROM medecin m, rendezvous r, patient p WHERE m.DRID = r.DRID AND p.PAID = r.PAID GROUP BY m.DRNOM, r.RVDDEBUT, p.PANOM;
SELECT DISTINCT PANOM, PAPRENOM, DRNOM, DRPRENOM FROM patient p, medecin m, rendezvous r WHERE r.PAID = p.PAID AND m.DRID = r.DRID;
SELECT DRNOM Medecin, SENOM Secretaire, RVDDEBUT Date_RDV FROM medecin m, secretaire s, rendezvous r WHERE r.RVDDEBUT > TO_DATE('2020-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') AND m.DRID = r.DRID AND s.SEID = r.SEID;
SELECT PANOM Patient, DRNOM Medecin, ORDESCRIPT Ordonnance FROM medecin m, patient p, ordonnance o WHERE p.PAID =o.PAID AND m.DRID = o.DRID;

